apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app-namespace
type: Opaque
data:
  # password: SuperSecretPass123 (base64 → U3VwZXJTZWNyZXRQYXNzMTIz)
  password: U3VwZXJTZWNyZXRQYXNzMTIz
