version: "3.8"
services:
  escape:
    build: .
    privileged: true
    # Монтирование Docker-сокета хоста – это основная уязвимость!
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    labels:
      scenario: cont-escape
