apiVersion: v1
kind: Pod
metadata:
  name: monitoring-safe
  namespace: default
  labels:
    app: monitoring
spec:
  containers:
  - name: monitor
    image: alpine:3.16
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    command: ["sh", "-c", "sleep 3600"]
