# Уязвимый Dockerfile: простое приложение на Python, которое просто выводит сообщение
FROM python:3.9-slim
WORKDIR /app
# COPY . /app
# CMD ["python", "-c", "print('Запущено приложение, но данные из /sensitive доступны!')"]
CMD ["sh", "-c", "sleep 3600"]
