apiVersion: v1
kind: Pod
metadata:
  name: sensitive-pod-fixed
  labels:
    app: sensitive
spec:
  containers:
  - name: sensitive-container
    image: alpine:3.16
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: safe-cache
      mountPath: /host-etc
  volumes:
  - name: safe-cache
    emptyDir: {}
